import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./providers";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'LastWord69ANIMA',
  description: 'Generated by create next app',
}

export default function RootLayout({
   children, 
  }: { 
    children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body 
        className={inter.className}
      >
        <Providers>
          {children}
          <Analytics />
          <SpeedInsights />
        </Providers>
      </body>
    </html>
  );
}